# Timeout in seconds that Limine will use before automatically booting.
timeout: 0

# The entry name that will be displayed in the boot menu.
/Limine Template
    # We use the Limine boot protocol.
    protocol: limine
    kaslr: no
    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/Cryptix.elf
    module_path: boot():/ksyms.sym
    module_cmdline: ksyms
    module_path: boot():/init
    module_cmdline: init
    module_path: boot():/initrd.img.gz
    module_cmdline: initrd

